# https://travis-ci.org/ankitpopli1891/django-autotranslate
language:
    python
python:
    - 3.6
env:
    - TOX_ENV=dj18-py27
    - TOX_ENV=dj18-py33
    - TOX_ENV=dj18-py34
    - TOX_ENV=dj18-py35
    - TOX_ENV=dj19-py27
    - TOX_ENV=dj19-py34
    - TOX_ENV=dj19-py35
    - TOX_ENV=dj110-py27
    - TOX_ENV=dj110-py34
    - TOX_ENV=dj110-py35
    - TOX_ENV=dj111-py27
    - TOX_ENV=dj111-py34
    - TOX_ENV=dj111-py35
    - TOX_ENV=dj111-py36
    - TOX_ENV=dj20-py34
    - TOX_ENV=dj20-py35
    - TOX_ENV=dj20-py36
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
matrix:
    fast_finish: true
branches:
    only:
        - master
